### ISSUE TITLE
Unable to load webknossos hosted zarr datasets

### ISSUE THREAD

**Issue by jstriebel** [ome/napari-ome-zarr#66] opened 2022-08-12 15:28 UTC
When testing to load ome/zarr data from [webknossos](https://webknossos.org/), I could not see any data, everything is shown black. This might be due to 1) Fortran (column-major) order data, and/or 2) the dimension order cxyz.

## Steps to reproduce:
1. I adapted `filename_patterns` in `napari.yaml` of this plugin to be able to open the webknossos zarr-streamed datasets (e.g. adding `https://*.webknossos.org/data/zarr/*`)
2. Opening any of these datasets does not show any data:
  * `python3 -m napari "https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color"`
  * `python3 -m napari "https://data-humerus.webknossos.org/data/zarr/scalable_minds/skin/color"`
  
Please note that the datasets for the different resolutions can be loaded via zarr-python, e.g. using 
```python
zarr.open_array("https://data-humerus.webknossos.org/data/zarr/scalable_minds/skin/color/1")
```

Additional info:
```
$ cat /etc/debian_version 
10.12
$ python --version
Python 3.8.11
$ napari --version
napari version 0.4.16
$ pip3 list | grep napari-ome-zarr
napari-ome-zarr                   0.5.2
```

**Comment by will-moore** [comment] 2022-08-15 21:21
Looking at https://ome.github.io/ome-ngff-validator/?source=https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color I can see that the `/1/.zarray` has:
```"dimension_seperator": "."``` whereas for OME-NGFF versions 0.2 and above, a `/` is expected as the dimension separator.

And running napari as you did...

```
$ napari --plugin napari-ome-zarr https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color -vvv
...
22:18:03 DEBUG Created nested FSStore(https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color/labels, r, {'dimension_separator': '/', 'normalize_keys': False})
...
22:15:46 DEBUG https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color/4-4-2/0/8/25/15
```

I noticed that opening in vizarr, https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color I see a lot of 404s for URLs like:
`https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color/4-4-2/0.0.1.0`, so it's being less picky about the separator, but still not finding chunks.

**Comment by normanrz** [comment] 2022-08-16 13:46
I also just learned last week that `.` is not allowed as dimension separator in OME-Zarr. To me that is a bit weird, because the underlying Zarr spec supports both separators and, therefore, many OME-Zarr implementations also do. Anyways, that is probably something we should propose for version 0.5.

Btw, the dataset opens well in [Neuroglancer](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1.124e-8%2C%22m%22%5D%2C%22y%22:%5B1.124e-8%2C%22m%22%5D%2C%22z%22:%5B2.8e-8%2C%22m%22%5D%7D%2C%22position%22:%5B1768.7923583984375%2C1355.0789794921875%2C276.5%5D%2C%22crossSectionScale%22:0.9784169501582856%2C%22projectionOrientation%22:%5B0.039588648825883865%2C0.07244931906461716%2C-0.03900988772511482%2C0.9958223104476929%5D%2C%22projectionScale%22:5364.740891379979%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4dense_motta_et_al_demo/color/%22%2C%22localDimensions%22:%7B%22c%27%22:%5B1%2C%22%22%5D%7D%2C%22localPosition%22:%5B0.5%5D%2C%22tab%22:%22rendering%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B80%2C169%5D%7D%7D%2C%22name%22:%22raw%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22zarr://https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4dense_motta_et_al_demo/segmentation/%22%2C%22localDimensions%22:%7B%22c%27%22:%5B1%2C%22%22%5D%7D%2C%22localPosition%22:%5B0.5%5D%2C%22tab%22:%22source%22%2C%22selectedAlpha%22:0.28%2C%22name%22:%22segmentation%22%7D%5D%2C%22selectedLayer%22:%7B%22size%22:514%2C%22layer%22:%22raw%22%7D%2C%22layout%22:%224panel%22%2C%22selection%22:%7B%22size%22:514%2C%22visible%22:false%7D%7D).

**Comment by jstriebel** [comment] 2022-08-16 15:07
> I noticed that opening in vizarr, https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color I see a lot of 404s for URLs like:
> `https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color/4-4-2/0.0.1.0`, so it's being less picky about the separator, but still not finding chunks.

This is due to an offset of the data, which just starts at `x, y, z = 2679, 4224, 1719`, the first chunks are all empty.

**Comment by joshmoore** [comment] 2022-09-12 15:21
Other than https://github.com/ome/ngff/issues/135 are there any actions here?

**Comment by will-moore** [comment] 2022-11-11 13:38
I was going to start looking at a fix here, but I can't even get as far as I did above https://github.com/ome/napari-ome-zarr/issues/66#issuecomment-1215844993

```
(napari) Williams-MacBook-Pro:napari-ome-zarr wmoore$ napari --plugin napari-ome-zarr https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color
Traceback (most recent call last):
  File "/Users/wmoore/opt/anaconda3/envs/napari/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/wmoore/opt/anaconda3/envs/napari/lib/python3.9/site-packages/napari/__main__.py", line 446, in main
    _run()
  File "/Users/wmoore/opt/anaconda3/envs/napari/lib/python3.9/site-packages/napari/__main__.py", line 311, in _run
    viewer._window._qt_viewer._qt_open(
  File "/Users/wmoore/opt/anaconda3/envs/napari/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 754, in _qt_open
    self.viewer.open(
  File "/Users/wmoore/opt/anaconda3/envs/napari/lib/python3.9/site-packages/napari/components/viewer_model.py", line 931, in open
    self._add_layers_with_plugins(
  File "/Users/wmoore/opt/anaconda3/envs/napari/lib/python3.9/site-packages/napari/components/viewer_model.py", line 1134, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/Users/wmoore/opt/anaconda3/envs/napari/lib/python3.9/site-packages/napari/plugins/io.py", line 86, in read_data_with_plugins
    raise ValueError(
ValueError: There is no registered plugin named 'napari-ome-zarr'.
Names of plugins offering readers are: {'builtins', 'ome-types'}
```

I assume that this in `napari.yml` means that the plugin is not used to open the file (even though I'm specifying it on the command line): 

```
      filename_patterns:
        - "*.zarr"
        - "*.zarr*"
```

since the URL contains `/zarr/` but not `.zarr`.

**Comment by joshmoore** [comment] 2022-11-11 13:45
cc: @DragaDoncila in case there's any way to let users override the patterns.

**Comment by normanrz** [comment] 2022-11-11 13:46
I know there is a discussion in zarr v3 to make `.zarr` suffixes mandatory, but is this already a requirement in the OME-NGFF spec?

**Comment by joshmoore** [comment] 2022-11-11 13:48
Not currently an NGFF requirement, no. In this case it's a napari mechanism for filtering inputs to plugins.

**Comment by will-moore** [comment] 2022-11-11 14:04
@jstriebel with the fix at https://github.com/ome/ome-zarr-py/pull/235 and the `filename_pattern` change to allow ``` "*zarr*" ```, I can open in napari with:

```
$ napari --plugin napari-ome-zarr https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color -vvv
```
I see chunks loaded using `.` separator, but I can't see anything in napari (playing with rendering settings and trying different slider positions).

![Screenshot 2022-11-11 at 13 51 35](https://user-images.githubusercontent.com/900055/201354178-640a6b0a-3e73-4cc1-9b6e-574ce5314fc8.png)

And testing with vizarr as above gives 404s for ALL the chunk URLs. e.g. `https://data-humerus.webknossos.org/data/zarr/scalable_minds/l4_sample_dev/color/4-4-2/0.0.18.23`.

Any ideas?

**Comment by normanrz** [comment] 2022-11-11 14:05
That dataset has an implicit offset. Can check a location starting from x, y, z = 2679, 4224, 1719?

**Comment by will-moore** [comment] 2022-11-11 14:31
Ah, thanks - I found it eventually!

![Screenshot 2022-11-11 at 14 30 15](https://user-images.githubusercontent.com/900055/201361082-1042a0ca-8eec-4904-aeee-3c535a785d24.png)

**Comment by DragaDoncila** [comment] 2022-11-11 19:50
> cc: @DragaDoncila in case there's any way to let users override the patterns.

Iirc through the command line you *could* assign a preference for a filename pattern to a plugin, even if that reader doesn't declare that filename pattern in its list.

```python
from napari.settings import get_settings
get_settings().plugins.extension2reader['*blah*] = 'not-a-blah-reader' 
```

I haven't fully explored that behaviour to see if we would actually try the plugin, but I think we might? I'm travelling atm so can't investigate.

We also need to improve that error message about no registered plugin, since it's very misleading.

**Comment by joshmoore** [comment] 2022-11-15 12:11
Thanks, @DragaDoncila. (Safe travels). Perhaps printing ... all patterns(?), similar patterns(?!) would help users. "Did you mean `/zarr/`"?

**Comment by DragaDoncila** [comment] 2022-11-22 21:45
@joshmoore do you mean on the napari side when a user tries to read a file and it kinda matches a filename pattern but not quite? I'm not sure what heuristic we could use to determine this approximate match but there are options out there. It's something we could consider, but would just want to be very careful about the information being actually useful. If there's a slight difference in file extension but a huge difference in the actual file format, we wouldn't want a user thinking they can just tweak the extension and the plugin would work.

**Comment by dstansby** [comment] 2024-07-16 11:08
Can this be closed? It's not entirely clear from the thread above whether there is still an issue - if there is, could someone post a small self-contained reproducible code snippet that illustrates the issue?

**Comment by joshmoore** [comment] 2024-07-16 12:08
Thanks, @dstansby. Closing makes sense to me. If anyone disagrees, please say the word.

**Closed by joshmoore** 2024-07-16 12:08 UTC
